#!/bin/bash
#SBATCH -A sc5fp4p # 2017 XSEDE Applications of Parallel Computing Course Allocation
#SBATCH -J auto-particle-serial
#SBATCH -o auto-particle-serial.stdout
#SBATCH -n 1         
#SBATCH -p RM
#SBATCH -t 00:10:00
#SBATCH -N 1         
     
rm serial_sum.txt
./serial -n 500 -no -s serial_sum.txt
./serial -n 1000 -no -s serial_sum.txt
./serial -n 2000 -no -s serial_sum.txt
./serial -n 3000 -no -s serial_sum.txt
./serial -n 4000 -no -s serial_sum.txt
./serial -n 6000 -no -s serial_sum.txt
./serial -n 8000 -no -s serial_sum.txt
./serial -n 10000 -no -s serial_sum.txt
./serial -n 15000 -no -s serial_sum.txt
./serial -n 20000 -no -s serial_sum.txt
./serial -n 35000 -no -s serial_sum.txt
./serial -n 50000 -no -s serial_sum.txt
./serial -n 100000 -no -s serial_sum.txt
./autograder -v serial -s serial_sum.txt

